import { Html, Head, Main, NextScript } from "next/document";
import type {  ReactNode } from "react";

type Props = {
  children: ReactNode;
};

export default function Document() {
  return (
    <Html>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicons_black/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicons_black/favicon-16x16.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Zen+Kaku+Gothic+New:wght@300;400;500;700;900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
