name: CI

on:
  pull_request:
    paths:
      - 'src/**'
      - '.eslintrc.json'
      - 'package.json'
      - '.prettierrc.json'
      - 'yarn.lock'
      - '.github/workflows/build.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare file
        run: |
          cp .env.tmpl .env

      - name: Install deps
        run: yarn

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

